- id: eslint
  name: eslint
  entry: eslint
  language: node
  files: \.jsx?$
  args: []

  # Use additional_dependencies to install the actual node package
  additional_dependencies:
    [
      "eslint@5.16.0",
      "eslint-plugin-import@2.17.2",
      "eslint-plugin-mocha@4.11.0",
      "eslint-plugin-react@7.12.4",
      "babel-eslint@8.2.6",
    ]
  minimum_pre_commit_version: 0.7.0
